In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.DataFrame({
    "Name":["Anmol","Ajay"],
    "Class":[10,np.nan]
})

In [4]:
data.head()

    Name  Class
0  Anmol   10.0
1   Ajay    NaN

In [5]:
print(data.isnull())             # Here we get a dataframe or series showing whether any given cell is null or not

    Name  Class
0  False  False
1  False   True

In [6]:
data.isnull().sum()             #The .sum() actually adds the value of those isna() values which are true

Name     0
Class    1
dtype: int64

In [7]:
#attribute
data.shape          # this is a stored property of the data frame so no parenthesis

(2, 2)

In [8]:
#funtion or method 
data.info()          #this belong to the obejct and is capable of taking parameters and producing relevant results

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      object
 1   Class   1 non-null      float64
dtypes: float64(1), object(1)
memory usage: 164.0+ bytes

In [9]:
data=pd.read_csv("customer_segmentation.csv")

In [10]:
data.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [11]:
data.shape

(2240, 29)

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), object(3)
memory usage: 507.6+ KB

In [13]:
data['Dt_Customer']=pd.to_datetime(data['Dt_Customer'],format='%d-%m-%Y')

In [14]:
data

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,2013-06-13,46,709,...,5,0,0,0,0,0,0,3,11,0
2236,4001,1946,PhD,Together,64014.0,2,1,2014-06-10,56,406,...,7,0,0,0,1,0,0,3,11,0
2237,7270,1981,Graduation,Divorced,56981.0,0,0,2014-01-25,91,908,...,6,0,1,0,0,0,0,3,11,0
2238,8235,1956,Master,Together,69245.0,0,1,2014-01-24,8,428,...,3,0,0,0,0,0,0,3,11,0
2239,9405,1954,PhD,Married,52869.0,1,1,2012-10-15,40,84,...,7,0,0,0,0,0,0,3,11,1

In [15]:
data.shape

(2240, 29)

In [16]:
data['Age']=2026-data['Year_Birth']

In [17]:
data=data[(data['Age']<90) & (data['Income']<100000)]

In [18]:
data.shape

(2200, 30)

In [45]:
data['Total_Mnt'] = data['MntWines'] + data['MntFruits'] + data['MntMeatProducts'] + data['MntFishProducts'] + data['MntSweetProducts'] + data['MntGoldProds']
data['Total_Purchases'] = data['NumWebPurchases'] + data['NumCatalogPurchases'] + data['NumStorePurchases']
data['Children'] = data['Kidhome'] + data['Teenhome']
data['Family_Size'] = data['Marital_Status'].replace({'Married': 2, 'Together': 2, 'Single': 1, 'Divorced': 1, 'Widow': 1, 'Alone': 1, 'Absurd': 1, 'YOLO': 1}) + data['Children']

C:\Users\riddh\AppData\Local\Temp\ipykernel_13332\2552782457.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Total_Mnt'] = data['MntWines'] + data['MntFruits'] + data['MntMeatProducts'] + data['MntFishProducts'] + data['MntSweetProducts'] + data['MntGoldProds']
C:\Users\riddh\AppData\Local\Temp\ipykernel_13332\2552782457.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Total_Purchases'] = data['NumWebPurchases'] + data['NumCatalogPurchases'] + data['NumStorePurchases']
C:\Users\riddh\AppData\Local\Temp\ipykernel_13332\2552782457.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Children'] = data['Kidhome'] + data['Teenhome']
C:\Users\riddh\AppData\Local\Temp\ipykernel_13332\2552782457.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Family_Size'] = data['Marital_Status'].replace({'Married': 2, 'Together': 2, 'Single': 1, 'Divorced': 1, 'Widow': 1, 'Alone': 1, 'Absurd': 1, 'YOLO': 1}) + data['Children']
C:\Users\riddh\AppData\Local\Temp\ipykernel_13332\2552782457.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Family_Size'] = data['Marital_Status'].replace({'Married': 2, 'Together': 2, 'Single': 1, 'Divorced': 1, 'Widow': 1, 'Alone': 1, 'Absurd': 1, 'YOLO': 1}) + data['Children']

In [51]:
cols = ['Age', 'Income', 'Total_Mnt', 'Total_Purchases','Family_Size','Recency','Children']
print(data[cols].describe().T)

                  count          mean           std     min      25%      50%  \
Age              2200.0     57.097727     11.702349    30.0     49.0     56.0
Income           2200.0  51500.314545  20577.132323  1730.0  35178.0  51222.5
Total_Mnt        2200.0    605.706364    601.492111     5.0     69.0    396.5
Total_Purchases  2200.0     12.535455      7.152317     0.0      6.0     12.0
Family_Size      2200.0      2.596364      0.905134     1.0      2.0      3.0
Recency          2200.0     49.041818     28.932517     0.0     24.0     49.0
Children         2200.0      0.950909      0.748714     0.0      0.0      1.0

                      75%      max
Age                 67.00     86.0
Income           68130.00  98777.0
Total_Mnt         1043.25   2525.0
Total_Purchases     18.00     32.0
Family_Size          3.00      5.0
Recency             74.00     99.0
Children             1.00      3.0

In [49]:
cols = ['Age', 'Income', 'Total_Mnt', 'Total_Purchases','Family_Size','Recency','Children']
print(data[cols].describe().T[['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']])

                  count          mean           std     min      25%      50%  \
Age              2200.0     57.097727     11.702349    30.0     49.0     56.0
Income           2200.0  51500.314545  20577.132323  1730.0  35178.0  51222.5
Total_Mnt        2200.0    605.706364    601.492111     5.0     69.0    396.5
Total_Purchases  2200.0     12.535455      7.152317     0.0      6.0     12.0
Family_Size      2200.0      2.596364      0.905134     1.0      2.0      3.0
Recency          2200.0     49.041818     28.932517     0.0     24.0     49.0
Children         2200.0      0.950909      0.748714     0.0      0.0      1.0

                      75%      max
Age                 67.00     86.0
Income           68130.00  98777.0
Total_Mnt         1043.25   2525.0
Total_Purchases     18.00     32.0
Family_Size          3.00      5.0
Recency             74.00     99.0
Children             1.00      3.0

In [53]:
data[cols]

      Age   Income  Total_Mnt  Total_Purchases  Family_Size  Recency  Children
0      69  58138.0       1617               22            1       58         0
1      72  46344.0         27                4            3       38         2
2      61  71613.0        776               20            2       26         0
3      42  26646.0         53                6            3       26         1
4      45  58293.0        422               14            3       94         1
...   ...      ...        ...              ...          ...      ...       ...
2235   59  61223.0       1341               16            3       46         1
2236   80  64014.0        444               15            5       56         3
2237   45  56981.0       1241               18            1       91         0
2238   70  69245.0        843               21            3        8         1
2239   72  52869.0        172                8            4       40         2

[2200 rows x 7 columns]

In [55]:
data[cols].T

,0,1,2,3,4,5,6,7,8,9,...,2229,2230,2231,2232,2234,2235,2236,2237,2238,2239
Age,69.0,72.0,61.0,42.0,45.0,59.0,55.0,41.0,52.0,76.0,...,54.0,42.0,56.0,40.0,52.0,59.0,80.0,45.0,70.0,72.0
Income,58138.0,46344.0,71613.0,26646.0,58293.0,62513.0,55635.0,33454.0,30351.0,5648.0,...,24434.0,11012.0,44802.0,26816.0,34421.0,61223.0,64014.0,56981.0,69245.0,52869.0
Total_Mnt,1617.0,27.0,776.0,53.0,422.0,716.0,590.0,169.0,46.0,49.0,...,50.0,84.0,1049.0,22.0,30.0,1341.0,444.0,1241.0,843.0,172.0
Total_Purchases,22.0,4.0,20.0,6.0,14.0,20.0,17.0,8.0,5.0,1.0,...,5.0,6.0,25.0,3.0,3.0,16.0,15.0,18.0,21.0,8.0
Family_Size,1.0,3.0,2.0,3.0,3.0,3.0,2.0,3.0,3.0,4.0,...,4.0,2.0,1.0,1.0,3.0,3.0,5.0,1.0,3.0,4.0
Recency,58.0,38.0,26.0,26.0,94.0,16.0,34.0,32.0,19.0,68.0,...,9.0,82.0,71.0,50.0,81.0,46.0,56.0,91.0,8.0,40.0
Children,0.0,2.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,...,2.0,1.0,0.0,0.0,1.0,1.0,3.0,0.0,1.0,2.0

In [69]:
from sklearn.preprocessing import StandardScaler
features=['Income','Total_Mnt','Total_Purchases','Age','Children']
scaler=StandardScaler()
scaled_ft=scaler.fit(data[features])

In [71]:
scaled_ft

StandardScaler()

In [75]:
scaler.mean_

array([5.15003145e+04, 6.05706364e+02, 1.25354545e+01, 5.70977273e+01,
       9.50909091e-01])

In [79]:
sct1=scaler.transform(data[features])

In [81]:
sct2=scaler.fit_transform(data[features])

In [83]:
sct1

array([[ 0.32264916,  1.68169048,  1.32358477,  1.01731531, -1.27034582],
       [-0.25064167, -0.9623367 , -1.19365454,  1.27373238,  1.40150963],
       [ 0.9776512 ,  0.28318302,  1.04389151,  0.33353645, -1.27034582],
       ...,
       [ 0.26640891,  1.05643625,  0.76419826, -1.03402127, -1.27034582],
       [ 0.86254583,  0.394598  ,  1.18373814,  1.10278767,  0.06558191],
       [ 0.06653   , -0.72121472, -0.63426802,  1.27373238,  1.40150963]])

In [85]:
sct2

array([[ 0.32264916,  1.68169048,  1.32358477,  1.01731531, -1.27034582],
       [-0.25064167, -0.9623367 , -1.19365454,  1.27373238,  1.40150963],
       [ 0.9776512 ,  0.28318302,  1.04389151,  0.33353645, -1.27034582],
       ...,
       [ 0.26640891,  1.05643625,  0.76419826, -1.03402127, -1.27034582],
       [ 0.86254583,  0.394598  ,  1.18373814,  1.10278767,  0.06558191],
       [ 0.06653   , -0.72121472, -0.63426802,  1.27373238,  1.40150963]])